services:
  - type: web
    name: mern-blog-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: your_mongodb_uri
      - key: PORT
        value: 8080
